export const EMAIL_START = "EMAIL_LOGIN_START";
export const EMAIL_SUCCESS = "EMAIL_LOGIN_SUCCESS";
export const EMAIL_FAILURE = "EMAIL_LOGIN_FAILURE";
export const CART_DATA = "CART_DATA";
export const PROFILE_START = "PROFILE_START";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAILURE = "PROFILE_FAILURE";
